#!/bin/bash

envdir=rticonnectorenv

# First, clone the repository from github
git clone https://github.com/rticommunity/rticonnextdds-connector.git


echo "Preparing enviornment..."
virtualenv $envdir

cp rticonnextdds-connector/rticonnextdds_connector.py $envdir/lib/python2.7/
cp -R rticonnextdds-connector/lib/ $envdir/lib/python2.7/


echo "In order to run the tutorial examples, use the following command in every terminal"
echo ""
echo '. setenvironment'
echo ""

